---
title: Deploying with Shinyproxy and Golem
author: Robert Kalcik
date: '2019-08-22'
slug: []
draft: true
categories:
  - R
  - Shiny
tags:
  - deployment
image:
  caption: ''
  focal_point: ''
---

After hitting `golem::add_docker_shinyproxy` I had to edit the dockerfile and replace the last line with ...

Loading `golem` as a remote did not work so I fetched it from github. 

The full working dockerfile is

```{bash, eval = FALSE}
FROM rocker/tidyverse:3.6.0
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")'
RUN R -e 'remotes::install_cran("attempt")'
RUN R -e 'remotes::install_cran("DT")'
RUN R -e 'remotes::install_cran("glue")'
RUN R -e 'remotes::install_github("ThinkR-open/golem")'
RUN R -e 'remotes::install_cran("htmltools")'
RUN R -e 'remotes::install_cran("shiny")'
COPY communitymap_*.tar.gz /app.tar.gz


RUN R -e 'remotes::install_local("/app.tar.gz")'
EXPOSE 3838
CMD  ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0'); communitymap::run_app()"]

```

This way I could build the docker image running `docker build -t "community_map"`.


And then take the app for a spin using `docker run -p 3838:3838 community_map`. 

# Enter Shinyproxy

Let's navigate to the folder containing the shinyproxy jar file and the application.yml. 

The application.yaml should include a reference to our Shiny App: 

```
  - id: community_map
    container-cmd: ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0'); communitymap::run_app()"]
    container-image: community_map
```
Here we run `java -jar shinyproxy-2.3.0.jar` et voilá.

# Containerized Shinyproxy

Let's set up a docker network: 

`docker network create sp-example-net`

We use a combo of a new application.yml and dockerfile like so: 

```
FROM openjdk:8-jre

RUN mkdir -p /opt/shinyproxy/
RUN wget https://www.shinyproxy.io/downloads/shinyproxy-2.3.0.jar -O /opt/shinyproxy/shinyproxy.jar
COPY application.yml /opt/shinyproxy/application.yml

WORKDIR /opt/shinyproxy/
CMD ["java", "-jar", "/opt/shinyproxy/shinyproxy.jar"]
```


and 

```
proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
      internal-networking: true
  specs:
  - id: community_map
    container-cmd: ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0'); communitymap::run_app()"]
    container-image: community_map
    container-network: sp-example-net

logging:
  file:
    shinyproxy.log
```

Important is that we have   `proxy:docker:internal-networking: true` and that the apps are connected to the right container-network.



# Saving Docker Image

The docker image can be saved using 

```
docker save community_map | gzip > community_map.tar.gz
```

And the use `docker load` to fetch the image. 

# Connecting to the databse
 
Source: https://nickjanetakis.com/blog/docker-tip-35-connect-to-a-database-running-on-your-docker-host

Also: https://forums.docker.com/t/single-db-instance-with-multiple-apps/40106/3

And: https://docs.docker.com/storage/volumes/

Officially: https://www.openanalytics.eu/blog/2017/11/12/shinyproxy-1.0.2/

We need a custom bridge Docker network so that the DIA Dashbaord and the Community Map can access the SQLite database
